import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/Providers";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Read nonce injected by middleware.ts when CSP_STRICT=1
  const nonce = process.env.CSP_STRICT === '1'
    ? (await headers()).get('x-nonce') ?? undefined
    : undefined;
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
         {children}
        </Providers>
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{
            __html: `
      (function(){
        var t;
        function set(){
          var vh = window.innerHeight * 0.01;
          document.documentElement.style.setProperty('--app-vh', vh + 'px');
        }
        function debounced(){ clearTimeout(t); t = setTimeout(set, 100); }
        set();
        window.addEventListener('resize', debounced, { passive:true });
        window.addEventListener('orientationchange', function(){ setTimeout(set, 150); }, { passive:true });
      })();`,
          }}
        />
      </body>
    </html>
  );
}
