import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
         {children}
        </Providers>
        <script
          dangerouslySetInnerHTML={{
            __html: `
      (function(){
        function set(){
          var vh = window.innerHeight * 0.01;
          document.documentElement.style.setProperty('--app-vh', vh + 'px');
        }
        set();
        window.addEventListener('resize', set, { passive:true });
        window.addEventListener('orientationchange', set, { passive:true });
      })();`,
          }}
        />
      </body>
    </html>
  );
}
